runtime: php55
api_version: 1
threadsafe: yes

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /([^/]+\.php)
  script: \1

# Set de entry point  
- url: /
  script: index.html

  # Serve css scripts.
- url: /css
  static_dir: css
  
# Serve js scripts.
- url: /js
  static_dir: js

env_variables:
    MYSQL_USER: <USER>
    MYSQL_PASSWORD: <PASSWORD>
    MYSQL_DSN: mysql:dbname=<DB_NAME>;unix_socket=/cloudsql/<CONNECTION_NAME>
    
beta_settings:
    cloud_sql_instances: "<CONNECTION_NAME>"


